# Generated by Django 5.1.4 on 2024-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0004_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Męczyzna'), (3, 'Inna')], default=3, max_length=1),
        ),
    ]
