# Generated by Django 5.1.4 on 2025-01-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'Pozwala zobaczyć modele osoba innych właścicieli')]},
        ),
    ]
